// This file was generated by Lox.Tools.AstGenerator on 7/17/2019 11:45:18 PM
namespace Lox
{
    public abstract class Expr
    {
        public abstract TResult Accept<TResult>(IVisitor<TResult> visitor);
    }

    public interface IVisitor<out TResult>
    {
        TResult VisitBinaryExpr(Binary expr);
        TResult VisitGroupingExpr(Grouping expr);
        TResult VisitLiteralExpr(Literal expr);
        TResult VisitUnaryExpr(Unary expr);
    }

    public class Binary : Expr
    {
        public Expr Left { get; }
        public Token Op { get; }
        public Expr Right { get; }
    
        public Binary (Expr left, Token op, Expr right)
        {
            Left = left;
            Op = op;
            Right = right;
        }
    
        public override TResult Accept<TResult>(IVisitor<TResult> visitor)
        {
            return visitor.VisitBinaryExpr(this);
        }
    }

    public class Grouping : Expr
    {
        public Expr Expression { get; }
    
        public Grouping (Expr expression)
        {
            Expression = expression;
        }
    
        public override TResult Accept<TResult>(IVisitor<TResult> visitor)
        {
            return visitor.VisitGroupingExpr(this);
        }
    }

    public class Literal : Expr
    {
        public object Value { get; }
    
        public Literal (object value)
        {
            Value = value;
        }
    
        public override TResult Accept<TResult>(IVisitor<TResult> visitor)
        {
            return visitor.VisitLiteralExpr(this);
        }
    }

    public class Unary : Expr
    {
        public Token Op { get; }
        public Expr Right { get; }
    
        public Unary (Token op, Expr right)
        {
            Op = op;
            Right = right;
        }
    
        public override TResult Accept<TResult>(IVisitor<TResult> visitor)
        {
            return visitor.VisitUnaryExpr(this);
        }
    }
}
