// This file was generated by Lox.Tools.AstGenerator on 7/17/2019 9:53:01 PM
namespace Lox
{
    public abstract class Expr { }

    public class BinaryExpr : Expr
    {
        public Expr Left { get; }
        public Token Op { get; }
        public Expr Right { get; }
    
        public BinaryExpr (Expr left, Token op, Expr right)
        {
            Left = left;
            Op = op;
            Right = right;
        }
    }

    public class GroupingExpr : Expr
    {
        public Expr Expression { get; }
    
        public GroupingExpr (Expr expression)
        {
            Expression = expression;
        }
    }

    public class LiteralExpr : Expr
    {
        public object Value { get; }
    
        public LiteralExpr (object value)
        {
            Value = value;
        }
    }

    public class UnaryExpr : Expr
    {
        public Token Op { get; }
        public Expr Right { get; }
    
        public UnaryExpr (Token op, Expr right)
        {
            Op = op;
            Right = right;
        }
    }
}
