// This file was generated by Lox.Tools.AstGenerator on 9/4/2019 12:06:43 AM
using System.Collections.Generic;

namespace Lox
{
    public abstract class Expr
    {
        public abstract TResult Accept<TResult>(IExprVisitor<TResult> visitor);
    }

    public interface IExprVisitor<out TResult>
    {
        TResult VisitAssignExpr(Assign expr);
        TResult VisitBinaryExpr(Binary expr);
        TResult VisitGroupingExpr(Grouping expr);
        TResult VisitLiteralExpr(Literal expr);
        TResult VisitUnaryExpr(Unary expr);
        TResult VisitVariableExpr(Variable expr);
    }

    public class Assign : Expr
    {
        public Token Name { get; }
        public Expr Value { get; }
    
        public Assign (Token name, Expr value)
        {
            Name = name;
            Value = value;
        }
    
        public override TResult Accept<TResult>(IExprVisitor<TResult> visitor)
        {
            return visitor.VisitAssignExpr(this);
        }
    }

    public class Binary : Expr
    {
        public Expr Left { get; }
        public Token Op { get; }
        public Expr Right { get; }
    
        public Binary (Expr left, Token op, Expr right)
        {
            Left = left;
            Op = op;
            Right = right;
        }
    
        public override TResult Accept<TResult>(IExprVisitor<TResult> visitor)
        {
            return visitor.VisitBinaryExpr(this);
        }
    }

    public class Grouping : Expr
    {
        public Expr Expression { get; }
    
        public Grouping (Expr expression)
        {
            Expression = expression;
        }
    
        public override TResult Accept<TResult>(IExprVisitor<TResult> visitor)
        {
            return visitor.VisitGroupingExpr(this);
        }
    }

    public class Literal : Expr
    {
        public object Value { get; }
    
        public Literal (object value)
        {
            Value = value;
        }
    
        public override TResult Accept<TResult>(IExprVisitor<TResult> visitor)
        {
            return visitor.VisitLiteralExpr(this);
        }
    }

    public class Unary : Expr
    {
        public Token Op { get; }
        public Expr Right { get; }
    
        public Unary (Token op, Expr right)
        {
            Op = op;
            Right = right;
        }
    
        public override TResult Accept<TResult>(IExprVisitor<TResult> visitor)
        {
            return visitor.VisitUnaryExpr(this);
        }
    }

    public class Variable : Expr
    {
        public Token Name { get; }
    
        public Variable (Token name)
        {
            Name = name;
        }
    
        public override TResult Accept<TResult>(IExprVisitor<TResult> visitor)
        {
            return visitor.VisitVariableExpr(this);
        }
    }
}
