// This file was generated by Lox.Tools.AstGenerator on 7/22/2019 11:51:28 PM
namespace Lox
{
    public abstract class Stmt
    {
        public abstract TResult Accept<TResult>(IStmtVisitor<TResult> visitor);
    }

    public interface IStmtVisitor<out TResult>
    {
        TResult VisitExpressionStmt(Expression stmt);
        TResult VisitPrintStmt(Print stmt);
    }

    public class Expression : Stmt
    {
        public Expr Expr { get; }
    
        public Expression (Expr expr)
        {
            Expr = expr;
        }
    
        public override TResult Accept<TResult>(IStmtVisitor<TResult> visitor)
        {
            return visitor.VisitExpressionStmt(this);
        }
    }

    public class Print : Stmt
    {
        public Expr Expr { get; }
    
        public Print (Expr expr)
        {
            Expr = expr;
        }
    
        public override TResult Accept<TResult>(IStmtVisitor<TResult> visitor)
        {
            return visitor.VisitPrintStmt(this);
        }
    }
}
